---
title: "SCT Task 2"
author: "Michael Bohl"
date: "2024-04-24"
output: html_document
---

## IMPORTS, install libraries if needed
```{r}
required_libraries = c("Seurat", "Matrix", "dplyr", "patchwork")

# Check if each library is installed and install it if not
for (library_name in required_libraries) {
  if (!requireNamespace(library_name, quietly = TRUE)) {
    message(paste("Installing and loading library", library_name))
    install.packages(library_name)
  }
  library(library_name, character.only = TRUE)
}
```

## read in the data (rename the counts file to matrix.mtx.gtz)
```{r}
counts <- Read10X("./data", gene.column=1)
meta <- read.table("./data/meta.tsv.gz")
seurat <- CreateSeuratObject(counts, meta.data = meta)
```

## routine processing
```{r}
# Normalize, find variable features, remove cell cycle genes, and scale data
seurat <- NormalizeData(seurat) %>%
  FindVariableFeatures(nfeatures = 3000) %>%
  CellCycleScoring(s.features = cc.genes.updated.2019$s.genes,
                   g2m.features = cc.genes.updated.2019$g2m.genes)
VariableFeatures(seurat) <- setdiff(VariableFeatures(seurat),
                                    c(unlist(cc.genes.updated.2019),
                                    grep("^MT-", rownames(seurat), value=T)))
seurat <- ScaleData(seurat, vars.to.regress = c("G2M.Score","S.Score")) %>%
  RunPCA(npcs = 20) %>%
  RunUMAP(dims = 1:20)

plot1 <- UMAPPlot(seurat, group.by="organoid") & NoAxes()
plot2 <- FeaturePlot(seurat, c("FOXG1","EMX1","DLX2","MKI67"), order=T) & NoAxes() & NoLegend()
plot1 | plot2
```  

## trying out different integration methods

# Harmony
```{r}
library(harmony)
seurat_harmony <- RunHarmony(seurat, group.by.vars = "GLI3_status", nclust = 20)
seurat_harmony <- RunUMAP(seurat_harmony, reduction = "harmony", dims = 1:ncol(Embeddings(seurat_harmony,"harmony")), reduction.name = "umap_harmony", reduction.key = "UMAPHARM_")

# Visualize integrated data
plot1 <- DimPlot(seurat_harmony, reduction = "umap_harmony", group.by="GLI3_status") & NoAxes()
plot1 <- DimPlot(seurat_harmony, reduction = "umap_harmony", group.by="organoid") & NoAxes()
plot2 <- FeaturePlot(seurat_harmony,  c("FOXG1","EMX1","DLX2","MKI67"), reduction = "umap_harmony", order = T) & NoAxes() & NoLegend()
plot1 | plot2
```

# MNN integration didn't work yet
```{r}
#library(SeuratWrappers)
#seurat_samples <- SplitObject(seurat, "GLI3_status")
#seurat_mnn <- RunFastMNN(seurat_samples)
#seurat_mnn <- RunUMAP(seurat_mnn, reduction = "mnn", dims = 1:ncol(Embeddings(seurat,"mnn")), reduction.name = "umap_mnn", reduction.key = "UMAPMNN_")

# Visualize integrated data
#plot1 <- DimPlot(seurat_mnn, reduction = "umap_mnn", group.by="GLI3_status") & NoAxes()
#plot1 <- DimPlot(seurat_mnn, reduction = "umap_mnn", group.by="organoid") & NoAxes()
#plot2 <- FeaturePlot(seurat_mnn,  c("FOXG1","EMX1","DLX2","MKI67"), reduction = "umap_mnn", order = T) & NoAxes() & NoLegend()
#plot1 | plot2
```




# CSS
```{r}
library(simspec)
seurat <- cluster_sim_spectrum(seurat, label_tag = "organoid", cluster_resolution = 1)
seurat <- RunUMAP(seurat, reduction = "css", dims = 1:ncol(Embeddings(seurat,"css")), reduction.name = "umap_css", reduction.key = "UMAPCSS_")
plot1 <- DimPlot(seurat, reduction = "umap_css", group.by="GLI3_status") & NoAxes()
plot1 <- DimPlot(seurat, reduction = "umap_css", group.by="organoid") & NoAxes()
plot2 <- FeaturePlot(seurat, c("FOXG1","EMX1","DLX2","MKI67"), reduction = "umap_css", order=T) & NoAxes() & NoLegend()
plot1 | plot2

```
### Cluster and annotate data
```{r}
seurat <- FindNeighbors(seurat, reduction = "css", dims = 1:ncol(Embeddings(seurat,"css"))) %>%
  FindClusters(resolution = 0.9)

plot1 <- DimPlot(seurat, reduction = "umap_css", label = T) & NoAxes()
plot2 <- FeaturePlot(seurat, c("SOX2","DCX","FOXG1","EMX1","DLX2","MKI67","OTX2","HOXB2","TTR"),
                     reduction = "umap_css", order=T) & NoAxes() & NoLegend()
plot1 | plot2

seurat$region <- factor(setNames(c("ventral telen.",
                                   "ventral telen.",
                                   "non-telen.",
                                   "dorsal telen.",
                                   "non-telen.",
                                   "non-telen.",
                                   "non-telen.",
                                   "ventral telen.",
                                   "non-telen.",
                                   "dorsal telen.",
                                   "non-telen.",
                                   "ventral telen.",
                                   "non-telen.",
                                   "non-telen.",
                                   "non-telen.",
                                   "mixed",
                                   "dorsal telen.",
                                   "non-telen.",
                                   "dorsal telen."),
                                 levels(seurat@active.ident))[seurat@active.ident],
                        levels=c("dorsal telen.","ventral telen.","non-telen.","mixed"))
plot1 <- DimPlot(seurat, reduction = "umap_css", group.by = "region") & NoAxes()
plot2 <- FeaturePlot(seurat, c("SOX2","DCX","FOXG1","EMX1","DLX2","MKI67","OTX2","HOXB2","TTR"),
                     reduction = "umap_css", order=T) & NoAxes() & NoLegend()
plot1 | plot2

```


